project:
  type: website
  output-dir: docs

website:
  title: "GitHub For The Real World"
  back-to-top-navigation: true
  navbar:
    pinned: true
    search: true
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - text: "Tools"
        menu: 
          - href: tools/r_installation.qmd
            text: "R Installation"
      - href: tasks_overview.qmd
        text: Course Tasks
      - text: "Unit 1"
        menu: 
          - text: "Lesson 1: Intro to GitHub"
            href: lessons/unit_01/lesson_01/lesson_01.qmd
          - text: "Lesson 2: Creating your GitHub Profile README"
            href: lessons/unit_01/lesson_02/lesson_02.qmd
          - text: "Lesson 3: Markdown"
            href: lessons/unit_01/lesson_03/lesson_03.qmd
          - text: "Lesson 4: Additional Profile README Features"
            href: lessons/unit_01/lesson_04/lesson_04.qmd
          - text: "Lesson 5: Organizing Your Github Repository"
            href: lessons/unit_01/lesson_05/lesson_05.qmd
      - text: "Unit 2"
        menu: 
          - text: "Lesson 1: Intro to VSCode"
            href: lessons/unit_02/lesson_01/lesson_01.qmd
          - text: "Lesson 2: Intro to Quarto"
            href: lessons/unit_02/lesson_02/lesson_02.qmd
          - text: "Lesson 3: Git in VSCode"
            href: lessons/unit_02/lesson_03/lesson_03.qmd
            
      - text: "Unit 3"
        menu:
          - text: "Lesson 1: Create Your First Website"
            href: lessons/unit_03/lesson_01/lesson_01.qmd
          - text: "Lesson 2: Hosting Your Website on GitHub Pages"
            href: lessons/unit_03/lesson_02/lesson_02.qmd
          - text: "Lesson 3: Subpages and Nav Bars"
            href: lessons/unit_03/lesson_03/lesson_03.qmd
      - text: "Unit 4"
      - text: "Bonus Lessons"
        menu:
          - text: "Customizing Website Appearance with CSS"
            href: lessons/unit_bonus/css/customizing_css.qmd
      - text: "About the Authors"
        href: authors/authors.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    code-copy: true
    code-line-numbers: true
    code-block-border-left: "#A9A9A9"
    code-block-bg: true
    code-bloc-bg-alpha: -.2
    page-layout: full
    grid:
      sidebar-width: 200px
      body-width: 1030px
      margin-width: 70px

editor: visual