project:
  type: website
  output-dir: docs

website:
  title: "Github Pages Training"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Tools"
        menu: 
          - href: tools/r_installation.qmd
            text: "R Installation"
          - href: tools/r_studio.qmd
            text: "R Studio"
          - href: tools/git_installation.qmd
            text: "Git Installation"
          - href: tools/github_setup.qmd
            text: "Github Setup"
      - href: tasks_overview.qmd
        text: Course Tasks
      - text: "Unit 1"
        menu: 
          - text: "Lesson 1: Intro to GitHub"
            href: lessons\unit_01\lesson_01\lesson_01.qmd
          - text: "Lesson 2: Creating your GitHub Profile README"
            href: lessons\unit_01\lesson_02\lesson_02.qmd
          - text: "Lesson 3: Markdown"
            href: lessons\unit_01\lesson_03\lesson_03.qmd
          - text: "Lesson 4: Additional Profile README Features"
            href: lessons\unit_01\lesson_04\lesson_04.qmd
      - text: "Unit 2"
        menu: 
          - text: "Lesson 1: Intro to VSCode"
            href: lessons\Unit 02\Lesson 01\lesson_01.qmd
          - text: "Lesson 2: Intro to Quarto"
            href: lessons\unit_02\lesson_02\lesson_02.qmd
          - text: "Lesson 3: Git in VSCode"
            href: lessons\Unit_2\lesson_03.qmd
          - text: "Lesson 4: Websites with Quarto"
            href: lessons\unit_02\Lesson_04\quarto_website.qmd
      - text: "Unit 3"
        menu: 
          - text: "Lesson 1"
            href: lessons\unit_03\lesson_01\lesson_01.qmd
          - text: "Lesson 2"
            href: lessons\unit_03\lesson_02\lesson_02.qmd
          - text: "Lesson 3"
            href: lessons\unit_03\lesson_03\lesson_03.qmd
          - text: "Lesson 4"
            href: lessons\unit_03\lesson_04\lesson_04.qmd
      - text: "Unit 4"
        menu: 
          - text: "Lesson 1"
            href: lessons\unit_04\lesson_01\lesson_01.qmd
          - text: "Lesson 2"
            href: lessons\unit_04\lesson_02\lesson_02.qmd
          - text: "Lesson 3"
            href: lessons\unit_04\lesson_03\lesson_03.qmd
          - text: "Lesson 4"
            href: lessons\unit_04\lesson_04\lesson_04.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    code-copy: true
    code-line-numbers: true
    code-block-border-left: "#A9A9A9"
    code-block-bg: true
    code-bloc-bg-alpha: -.2
    page-layout: full
    grid:
      sidebar-width: 200px
      body-width: 1030px
      margin-width: 70px

editor: visual