---
title: "Lesson 05: CSS"
format: html
---

# Brigham Work Here

Introduction

Before we get into CSS, let's take a step back. In web development there are three major languages: HTML, CSS, and JavaScript
HTML (HyperText Markup Language):

HTML is like the skeleton of a website. Imagine your body without any skin, just bones. HTML gives structure to web pages, like how bones give shape to your body. It tells the web browser what each part of the webpage is, like headings, paragraphs, images, and links. These parts are wrapped in tags, like labels, so the browser knows how to show them.

CSS (Cascading Style Sheets):

Now, think of CSS as the clothes and colors you put on the skeleton to make it look cool! CSS adds style and design to the webpage. It decides how things look, like the colors, fonts, spacing, and layout. It's like magic paint that changes how the webpage appears, making it look pretty and interesting.

So, HTML sets up the structure, and CSS makes it look awesome! They work together to create websites that are both organized and cool-looking, just like putting together a fun puzzle!


- this is how you use CSS in Quarto 

```yaml
---
title: "My Document"
format:
  html:
    css: styles.css
---
```





- making one off tweaks like changing background color or a single font style
- The theme lesson will incorporate all of these to make a theme template used for future projects
- The CSS one can be introducing common tags like <div> and <p>, and how to use their attributes? Then the theme lesson will get in to how to write CSS and make it useful?
- The css lesson should look at how to adjust the style.css file that gets created when building a quarto website





# Mfon Work Here