---
title: "Task 01 - My First GitHub Repo"
---

## Overview

Git is the world's [most popular version control system](https://www.accuwebhosting.com/blog/best-version-control-systems/) and Github is the most popular site for hosting code using git in the cloud. As a version control system, Git helps you keep your coding project files organized by keeping a record of when you edited files and tags them with short notes about what changes were made in the last iteration. This is particularly helpful when you are colaborating on a project with other programmers and need to stay tidy while working on the same files.

Github is a free web service for storing your version controlled code in the cloud. It allows you to access your code from anywhere and it provides a handy interface for tracking your code's changes over time. It also happens to have a handy service for hosting static websites for free on their platform.

In this task you will create a github account, create a repository, and clone that repository onto your local machine in Rstudio.

## Tasks

-   If you haven't already, get R, R Studio, and Git installed on your local machine.

    -   [How to Install R](r_installation.qmd)

    -   [How to Install R Studio](r_studio.qmd)

    -   [How to install Git](git_installation.qmd)

-   Register for a github account at [github.com](https://github.com/)

    -   Fill out this spreadsheet when you are done: [Spreadsheet](https://docs.google.com/spreadsheets/d/1WY0_HiSEAS21xDnJ9R4uFLLzYcpVfmyZlEL3QMsd5zM/edit?usp=sharing)

-   Read this article on what git is and why you should use it: [What is Git & Why Should You Use It?](https://www.nobledesktop.com/blog/what-is-git-and-why-should-you-use-it)

-   Create your first repo by following these steps:
